server:
  port: 8888

spring:
  main:
    allow-circular-references: true
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: https://dev-keycloak.test.emart-dtmp.com/auth/realms/Sample/protocol/openid-connect/certs
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
            default_schema: public
            jdbc.lob.non_contextual_creation: true


keycloak:
  realm: Sample
  auth-server-url: https://dev-keycloak.test.emart-dtmp.com
  ssl-required: external
  resource: sampleWeb
  credentials:
    provider: secret
    secret: 8QfZhhXCiqpCnh8iw8LlvBjroiQ6osCU
    use-resource-role-mappings: true
  autodetect-bearer-only: true

logging:
  config: classpath:logging/logback-spring.xml
  level:
    root: INFO
    com.example: DEBUG

